//! MCP (Model Context Protocol) tool server module (feature-gated: `mcp`).
//!
//! Provides MCP tools for BM25 search integration with LLM agents:
//! - `bm25_search` -- execute a BM25 query and return top-k results
//! - `bm25_index_stats` -- return index statistics (num_docs, vocab_size, method, params)
//!
//! Uses rmcp for MCP protocol handling with Streamable HTTP transport.

use std::sync::Arc;

use rmcp::handler::server::tool::ToolRouter;
use rmcp::handler::server::wrapper::Parameters;
use rmcp::model::{Implementation, ServerCapabilities, ServerInfo};
use rmcp::serde;
use rmcp::serde_json;
use rmcp::ServerHandler;

// Import for derive macro expansion and tool attribute
#[allow(unused_imports)]
use schemars;
use rmcp::tool;

use crate::index::BM25Index;

/// MCP tool parameters for `bm25_search`.
#[derive(Debug, serde::Deserialize, schemars::JsonSchema)]
pub struct SearchParams {
    /// The search query string.
    pub query: String,
    /// Number of top results to return (default: 10).
    #[serde(default = "default_top_k")]
    pub top_k: u32,
}

fn default_top_k() -> u32 {
    10
}

/// A single search result returned by MCP.
#[derive(Debug, serde::Serialize, serde::Deserialize)]
pub struct McpSearchResult {
    /// Document ID in the corpus.
    pub doc_id: u32,
    /// BM25 relevance score.
    pub score: f32,
}

/// MCP search response.
#[derive(Debug, serde::Serialize, serde::Deserialize)]
pub struct McpSearchResponse {
    /// The original query string.
    pub query: String,
    /// Matching documents sorted by descending score.
    pub results: Vec<McpSearchResult>,
    /// Number of results returned.
    pub count: usize,
}

/// MCP index stats response.
#[derive(Debug, serde::Serialize, serde::Deserialize)]
pub struct McpStatsResponse {
    /// Number of documents in the index.
    pub num_docs: u32,
    /// Number of unique terms in the vocabulary.
    pub vocab_size: u32,
    /// BM25 scoring variant name.
    pub method: String,
    /// Scoring parameters.
    pub params: McpParamsInfo,
}

/// Scoring parameters subset for MCP stats.
#[derive(Debug, serde::Serialize, serde::Deserialize)]
pub struct McpParamsInfo {
    pub k1: f32,
    pub b: f32,
    pub delta: f32,
}

/// MCP server handler holding a shared BM25 index.
pub struct Bm25McpService {
    /// Shared BM25 index for concurrent access.
    index: Arc<BM25Index>,
    /// The tool router generated by rmcp macros.
    tool_router: ToolRouter<Self>,
}

impl Bm25McpService {
    /// Create a new MCP service wrapping the given index.
    pub fn new(index: Arc<BM25Index>) -> Self {
        Self {
            index,
            tool_router: Self::tool_router(),
        }
    }
}

#[rmcp::tool_router]
impl Bm25McpService {
    /// Search the BM25 index with a query string and return the top-k most relevant documents.
    /// Returns document IDs and their BM25 relevance scores, sorted by descending score.
    /// Use this tool to find documents relevant to a natural language query.
    #[tool(name = "bm25_search")]
    fn bm25_search(
        &self,
        Parameters(params): Parameters<SearchParams>,
    ) -> Result<String, String> {
        if params.top_k == 0 {
            return Err("top_k must be > 0".to_string());
        }

        let results = self
            .index
            .search(&params.query, params.top_k as usize)
            .map_err(|e| e.to_string())?;

        let response = McpSearchResponse {
            query: params.query,
            results: results
                .doc_ids
                .iter()
                .zip(results.scores.iter())
                .map(|(&doc_id, &score)| McpSearchResult { doc_id, score })
                .collect(),
            count: results.doc_ids.len(),
        };

        serde_json::to_string_pretty(&response).map_err(|e| e.to_string())
    }

    /// Return statistics about the loaded BM25 index including document count,
    /// vocabulary size, scoring method, and parameter values.
    /// Use this tool to understand the characteristics of the loaded index.
    #[tool(name = "bm25_index_stats")]
    fn bm25_index_stats(&self) -> String {
        let params = self.index.params();
        let response = McpStatsResponse {
            num_docs: self.index.num_docs(),
            vocab_size: self.index.vocab_size(),
            method: params.method.to_string(),
            params: McpParamsInfo {
                k1: params.k1,
                b: params.b,
                delta: params.delta,
            },
        };

        serde_json::to_string_pretty(&response)
            .unwrap_or_else(|e| format!("{{\"error\": \"{}\"}}", e))
    }
}

#[rmcp::tool_handler]
impl ServerHandler for Bm25McpService {
    fn get_info(&self) -> ServerInfo {
        ServerInfo::new(ServerCapabilities::builder().enable_tools().build())
            .with_server_info(Implementation::new("bm25-turbo", env!("CARGO_PKG_VERSION")))
            .with_instructions(
                "BM25 Turbo -- the fastest BM25 information retrieval engine. \
                 Use bm25_search to query the index and bm25_index_stats to get index metadata.",
            )
    }
}

/// Create a Streamable HTTP MCP service mounted at `/mcp`.
///
/// Returns an `axum::Router` that handles MCP protocol requests.
/// The router can be merged with an existing Axum application.
#[cfg(feature = "server")]
pub fn mcp_router(index: Arc<BM25Index>) -> axum::Router {
    use rmcp::transport::streamable_http_server::session::local::LocalSessionManager;
    use rmcp::transport::streamable_http_server::{
        StreamableHttpServerConfig, StreamableHttpService,
    };

    let session_manager = Arc::new(LocalSessionManager::default());
    let config = StreamableHttpServerConfig {
        stateful_mode: false,
        json_response: true,
        ..Default::default()
    };

    let mcp_service = StreamableHttpService::new(
        move || Ok(Bm25McpService::new(index.clone())),
        session_manager,
        config,
    );

    axum::Router::new().route("/mcp", axum::routing::any_service(mcp_service))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::BM25Builder;

    fn test_index() -> Arc<BM25Index> {
        let index = BM25Builder::new()
            .build_from_corpus(&[
                "the quick brown fox",
                "the lazy dog",
                "brown fox jumps over the lazy dog",
            ])
            .expect("build test index");
        Arc::new(index)
    }

    #[test]
    fn mcp_search_returns_results() {
        let index = test_index();
        let service = Bm25McpService::new(index);
        let params = SearchParams {
            query: "quick".to_string(),
            top_k: 2,
        };
        let result = service.bm25_search(Parameters(params));
        assert!(result.is_ok());
        let json: McpSearchResponse = serde_json::from_str(&result.unwrap()).unwrap();
        assert_eq!(json.query, "quick");
        assert!(!json.results.is_empty());
        assert_eq!(json.count, json.results.len());
    }

    #[test]
    fn mcp_search_zero_top_k_returns_error() {
        let index = test_index();
        let service = Bm25McpService::new(index);
        let params = SearchParams {
            query: "quick".to_string(),
            top_k: 0,
        };
        let result = service.bm25_search(Parameters(params));
        assert!(result.is_err());
    }

    #[test]
    fn mcp_index_stats_returns_valid_json() {
        let index = test_index();
        let service = Bm25McpService::new(index);
        let result = service.bm25_index_stats();
        let stats: McpStatsResponse = serde_json::from_str(&result).unwrap();
        assert_eq!(stats.num_docs, 3);
        assert!(stats.vocab_size > 0);
        assert_eq!(stats.method, "Lucene");
        assert_eq!(stats.params.k1, 1.5);
        assert_eq!(stats.params.b, 0.75);
    }

    #[test]
    fn mcp_search_returns_ranked_results() {
        let index = test_index();
        let service = Bm25McpService::new(index);
        let params = SearchParams {
            query: "brown fox".to_string(),
            top_k: 3,
        };
        let result = service.bm25_search(Parameters(params));
        assert!(result.is_ok());
        let json: McpSearchResponse = serde_json::from_str(&result.unwrap()).unwrap();
        assert!(!json.results.is_empty(), "should return results");

        // Verify scores are in descending order (ranked).
        for window in json.results.windows(2) {
            assert!(
                window[0].score >= window[1].score,
                "results should be ranked by descending score: {} >= {}",
                window[0].score,
                window[1].score
            );
        }
    }

    #[test]
    fn mcp_service_tool_router_lists_tools() {
        let index = test_index();
        let service = Bm25McpService::new(index);
        let tools = service.tool_router.list_all();
        assert_eq!(tools.len(), 2);

        let names: Vec<&str> = tools.iter().map(|t| t.name.as_ref()).collect();
        assert!(names.contains(&"bm25_search"), "should contain bm25_search");
        assert!(
            names.contains(&"bm25_index_stats"),
            "should contain bm25_index_stats"
        );
    }
}
